SELECT * FROM dbo.FILES;
DROP TABLE FILES;

GO
CREATE TABLE FILES
(
	File_id INT IDENTITY(1, 1),   
	File_PATH varchar(200),
	UserId INT NOT NULL,
	Date_Time DATETIME DEFAULT CURRENT_TIMESTAMP,
	FOREIGN KEY (UserId) REFERENCES USERS(User_Id),
	PRIMARY KEY (File_id)
)
GO

