CREATE PROCEDURE SELECT_USER_ID
@ID INT
AS
SELECT * FROM dbo.USERS
WHERE User_Id = @ID


CREATE PROCEDURE SELECT_POST_ID
@ID INT
AS
SELECT * FROM dbo.POSTS
WHERE Post_Id = @ID

CREATE PROCEDURE SELECT_COMMENT_ID
@ID INT
AS
SELECT * FROM dbo.COMMENTS
WHERE Comment_Id = @ID


EXECUTE dbo.SELECT_USER_ID 17 ;